# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'AudienzziOSSDK'

project 'AudienzziOSSDK.xcodeproj'
project 'Examples/DemoSwiftApp/DemoSwiftApp.xcodeproj'

def prd_pods
  pod 'PrebidMobileGAMEventHandlers'
  pod 'PrebidMobile'
end

def gma_pods
  pod 'Google-Mobile-Ads-SDK'
end

def ima_pod
  pod 'GoogleAds-IMA-iOS-SDK'
end

target 'AudienzziOSSDK' do
  project 'AudienzziOSSDK.xcodeproj'
  use_frameworks!
  pod 'SQLite.swift', '~> 0.14.0'
  prd_pods
  target 'AudienzziOSSDKTests' do
    pod 'SQLite.swift', '~> 0.14.0'
    prd_pods
  end
end

target 'DemoSwiftApp' do
  project 'Examples/DemoSwiftApp/DemoSwiftApp.xcodeproj'
  use_frameworks!
  pod 'SQLite.swift', '~> 0.14.0'
  prd_pods
  ima_pod
  gma_pods
end

post_install do |pi|
   pi.pods_project.targets.each do |t|
     t.build_configurations.each do |config|
       config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
     end
   end
 end
