platform :ios, '12.0'

workspace 'AudienzziOSSDK'

project 'AudienzziOSSDK.xcodeproj'
project 'Examples/DemoSwiftApp/DemoSwiftApp.xcodeproj'

def prebid_pods
  pod 'PrebidMobileGAMEventHandlers', '2.3.0'
  pod 'PrebidMobile', '2.3.0'
end

def google_ads_pods
  pod 'Google-Mobile-Ads-SDK', '11.10.0'
  pod 'GoogleAds-IMA-iOS-SDK', '3.23.0'
end

def sqlite_pod
  pod 'SQLite.swift', '0.14.1'
end

target 'AudienzziOSSDK' do
  project 'AudienzziOSSDK.xcodeproj'
  use_frameworks!
  sqlite_pod
  prebid_pods
  target 'AudienzziOSSDKTests' do
    inherit! :search_paths
    sqlite_pod
    prebid_pods
  end
end

target 'DemoSwiftApp' do
  project 'Examples/DemoSwiftApp/DemoSwiftApp.xcodeproj'
  use_frameworks!
  sqlite_pod
  prebid_pods
  google_ads_pods
end


post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end
